// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "foq8BWrbTCdhT7wbv0HZYV1kzto704WM60xKlD6O4SD6shhlvyk87MBnl5ZQf33Mp354Wl";
}
}
}

